### ISSUE TITLE
Event Participation Dialogue

### ISSUE THREAD

**Issue by Tiedearnemann** [ASE-Projekte-WS-2021/ase-ws-21-servus#20]
# User story
As a user, I want to see a detail & participation page for an event, so I can check if the event data fits my needs.

# Acceptance criteria

- [ ] Create the participation bottom sheet with its relevant data
- [ ] Report to backend when the participation button was clicked and increment attendants
- [ ] Allow "participation recall" incl. full backend functionality (reset button and attendees)

**Comment by Shoggomo** [comment]
When a user registers for an event, the ID to this event needs to be saved locally (e.g., in SharedPreferences). This way the app can react to this. For example, block registration to other events and show an `unregister` button.
