### ISSUE TITLE
Create Tutorial for Adobe XD

### ISSUE THREAD

**Issue by Tiedearnemann** [ASE-Projekte-WS-2021/ase-ws-21-servus#43]
# User story
As a developer, I want to have a prototyping tool, so I can plan and (p)review my app in advance.

# Acceptance criteria
- [ ] Possibility to store images and videos into wiki
- [ ] Filled Github Wiki entry
- [ ] Sharing of the wiki link with the ASE course

**Comment by Tiedearnemann** [comment]
![151041130-d936a7f0-49e1-4d26-acf6-dc2ad34c411f](https://user-images.githubusercontent.com/53007064/151041244-0cef3c4f-fff6-4076-a1e5-8212e844c7db.jpg)

**Comment by MichelleLanzinger** [comment]
![2](https://user-images.githubusercontent.com/42041831/151042358-35e42e61-641b-4d82-a143-3ae7e22d88ee.JPG)

**Comment by Tiedearnemann** [comment]
![1](https://user-images.githubusercontent.com/53007064/151042607-1fa3095a-df2b-492d-bf53-c9e547afb5d6.PNG)

**Comment by Tiedearnemann** [comment]
![2](https://user-images.githubusercontent.com/53007064/151042831-39e6ca6c-7065-4cab-9914-23971766dcb4.PNG)

**Comment by Tiedearnemann** [comment]
![4](https://user-images.githubusercontent.com/53007064/151043936-118ae811-1873-420c-af19-c914e9cbb6f4.PNG)

**Comment by Tiedearnemann** [comment]
![5](https://user-images.githubusercontent.com/53007064/151046221-394d45a0-09d6-442e-aca2-085d1cb539d2.PNG)

**Comment by Tiedearnemann** [comment]
![6](https://user-images.githubusercontent.com/53007064/151046619-bc32c467-4d7b-42b6-8dc0-ffed8729eb37.PNG)

**Comment by Tiedearnemann** [comment]
![7](https://user-images.githubusercontent.com/53007064/151046999-7a6a81da-d279-4268-b70b-4620d1f24be0.PNG)

**Comment by Tiedearnemann** [comment]
![8](https://user-images.githubusercontent.com/53007064/151047331-a9561e3a-922b-49d8-a34b-4bfe1be07955.PNG)

**Comment by Tiedearnemann** [comment]
![9](https://user-images.githubusercontent.com/53007064/151047544-073afd83-45b1-4aae-8a13-9c11660334ab.PNG)

**Comment by Tiedearnemann** [comment]
![10](https://user-images.githubusercontent.com/53007064/151048558-bbf22963-bab1-4005-95f6-e4e6e4667de6.PNG)

**Comment by Tiedearnemann** [comment]
![11](https://user-images.githubusercontent.com/53007064/151049553-d3339545-2eae-4880-b92e-cfac799b07eb.PNG)

**Comment by Tiedearnemann** [comment]
![12](https://user-images.githubusercontent.com/53007064/151050183-87d47be7-e7bc-4de5-a93c-923f4b7cdbf4.PNG)

**Comment by Tiedearnemann** [comment]
![13](https://user-images.githubusercontent.com/53007064/151142699-01aec7e3-0f21-4467-b6eb-d5fd4a57ee6e.PNG)

**Comment by MichelleLanzinger** [comment]
![Rollen](https://user-images.githubusercontent.com/42041831/151143406-b9452829-8054-4230-9351-cc9008f37e51.JPG)

**Comment by Tiedearnemann** [comment]
![15](https://user-images.githubusercontent.com/53007064/151147006-227e88f3-a75d-479a-8f26-03bfe6499daf.PNG)

**Comment by Tiedearnemann** [comment]
![16a](https://user-images.githubusercontent.com/53007064/151147546-663869da-8656-49d1-8ae6-d7007cb058ca.PNG)

**Comment by MichelleLanzinger** [comment]
![password](https://user-images.githubusercontent.com/42041831/151147625-6367fe67-96be-4ef5-9821-d384d1572928.JPG)

**Comment by Tiedearnemann** [comment]
![17](https://user-images.githubusercontent.com/53007064/151149220-5a2e56e8-040f-4056-a3c9-f71603e31ca9.PNG)

**Comment by Tiedearnemann** [comment]
![18](https://user-images.githubusercontent.com/53007064/151149902-78cdf0e0-f7a9-4334-960e-3e8c48ee4786.PNG)
