### ISSUE TITLE
DarkMode Overhaul

### ISSUE THREAD

**Issue by Tiedearnemann** [ASE-Projekte-WS-2021/ase-ws-21-servus#44]
# User story
As a user, I want to have a bug-free UI, so I can explore the whole system without interferences.

# Acceptance criteria
- [ ] Enable flawless Dark-Light-Mode design
- [ ] BottomSheet have to stay the same height, regardless of the height of its content

**Comment by Shoggomo** [comment]
It'd be better to open a new issue for every bug. this way we can track them better.
