### ISSUE TITLE
Visual link between event(-marker) and withdraw button

### ISSUE THREAD

**Issue by Zeyku** [ASE-Projekte-WS-2021/ase-ws-21-servus#62]
# User story
As a user, I want to see a visual correlation between the "participation"-button and the event(-marker), so I can easily see which event I am attending.

# Acceptance criteria

- [ ] marker (event) I attend to is visually "linked" to the withdraw button

**Comment by Shoggomo** [comment]
Also I want to be able to preview other events, when attending one Event.
