### ISSUE TITLE
User profiles

### ISSUE THREAD

**Issue by Shoggomo** [ASE-Projekte-WS-2021/ase-ws-21-servus#69]
# User story
As a user, I want to share a profile about me and see others, so I can better connect to other people.

# Acceptance criteria

- [x] A user can create his/her own profile.
- [x] Can view others' attendants in Event details.
- [x] Can view others' profile cards in Event details.

**Comment by Shoggomo** [comment]
## Profile creation and upload
Profile is saved locally. Profile information are uploaded into Event document when attending/creating an Event.

## Profile Image
The image is uploaded using Firebase Storage and a URL to it is acquired, that is appended to the Event.

## Profile information
 - Name
 - Geburtsdatum
 - Profilbild
 - Studiengang
 - Geschlecht

**Comment by Tiedearnemann** [comment]
Potential Workflow for implementation of "ownership": Workaround for server sided User-IDs for local accounts

- SotA: User created an event and get's assigned automatically -> EventID is known by the app at one moment
- EventID can be safed to a second shared prefs key-value e.g. "ownEvent". This thereafter can be used to determine if an event is one's own when clicked --> load event creation dialog with filled data; or another's event --> load participation data
- Profile information of can be passed to a single database array "creator", can be read from by event participants
- Profile information of participants can be passed to a multi-item database array "attendees", can be read by other event participants as well
- TTL: When user deletes event // withdraws his/her participation at owning event, shared pref's item will be deleted & event will be deleted from database, disregarding pending/participating attendees

**Comment by Tiedearnemann** [comment]
Functional up to the point of profile pictures:

Suggested workflow:
- When an event gets created, a reffering folder in the storage (name = event UUID) will be created
- All Attendees will save their image to that specific folder (again, image name = attendee UUID) when attending
- All attendees can specificly delete their image when withdrawing
- Folder has to be deleted when event gets deleted
- Upload/Download code snippets are available in docu

Benefit(s):
- Always known references/paths
