### ISSUE TITLE
Can attend event, when already attending another event

### ISSUE THREAD

**Issue by Tiedearnemann** [ASE-Projekte-WS-2021/ase-ws-21-servus#78]
# User story
As a user, I want to have a running participate/withdraw mechanism, so I can participate and withdraw at different events - one at a time.
-> When currently participating and checking out different events, a user can withdraw and the counter of "number of participants" decrements from the wrong event id - currently always decrements from the selected event, not from the subscribed one.

# Acceptance criteria
- [x] Withdraw only from subsrcibed event.

**Comment by Shoggomo** [comment]
Possible solution:
Disable and grey out attend button, when already attending other event.
